"""removed signature hash

Revision ID: 00b8978b65d7
Revises: 42af5ac57d82
Create Date: 2026-01-20 10:15:56.813197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '00b8978b65d7'
down_revision: Union[str, Sequence[str], None] = '42af5ac57d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watermarks', 'signature_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watermarks', sa.Column('signature_hash', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
