"""refactor table 1

Revision ID: 20415591837a
Revises: 9b325acb766f
Create Date: 2025-12-28 20:08:44.061157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '20415591837a'
down_revision: Union[str, Sequence[str], None] = '9b325acb766f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watermarks', sa.Column('mime_type', sa.String(length=100), nullable=False))
    op.alter_column('watermarks', 'content_type',
               existing_type=mysql.ENUM('image', 'video', 'audio', 'document'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_watermarks_content_type'), 'watermarks', ['content_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watermarks_content_type'), table_name='watermarks')
    op.alter_column('watermarks', 'content_type',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('image', 'video', 'audio', 'document'),
               existing_nullable=False)
    op.drop_column('watermarks', 'mime_type')
    # ### end Alembic commands ###
