"""removed content has and avid

Revision ID: 296aba9f87bb
Revises: fce834c16a7a
Create Date: 2026-01-02 08:43:54.238062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '296aba9f87bb'
down_revision: Union[str, Sequence[str], None] = 'fce834c16a7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watermark_verify'), table_name='watermarks')
    op.create_index('ix_watermark_verify', 'watermarks', ['signature_hash', 'status'], unique=False)
    op.drop_column('watermarks', 'content_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watermarks', sa.Column('content_hash', mysql.VARCHAR(length=64), nullable=True))
    op.drop_index('ix_watermark_verify', table_name='watermarks')
    op.create_index(op.f('ix_watermark_verify'), 'watermarks', ['id', 'content_hash', 'status'], unique=False)
    # ### end Alembic commands ###
