"""ownerid

Revision ID: 42af5ac57d82
Revises: 296aba9f87bb
Create Date: 2026-01-03 08:55:47.998237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42af5ac57d82'
down_revision: Union[str, Sequence[str], None] = '296aba9f87bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watermark_verify'), table_name='watermarks')
    op.create_index('ix_watermark_verify', 'watermarks', ['owner_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_watermark_verify', table_name='watermarks')
    op.create_index(op.f('ix_watermark_verify'), 'watermarks', ['signature_hash', 'status'], unique=False)
    # ### end Alembic commands ###
