"""added content type

Revision ID: 8ab9310b722b
Revises: c6f96b334d3e
Create Date: 2025-12-28 13:10:40.778307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8ab9310b722b'
down_revision: Union[str, Sequence[str], None] = 'c6f96b334d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watermarks', sa.Column('content_type', sa.String(length=100), nullable=False))
    op.alter_column('watermarks', 'algorithm_version',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('watermarks', 'status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('watermarks', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.create_index('ix_watermark_verify', 'watermarks', ['asset_id', 'signature_hash', 'content_hash'], unique=False)
    op.create_index(op.f('ix_watermarks_owner_id'), 'watermarks', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watermarks_owner_id'), table_name='watermarks')
    op.drop_index('ix_watermark_verify', table_name='watermarks')
    op.alter_column('watermarks', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('watermarks', 'status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('watermarks', 'algorithm_version',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_column('watermarks', 'content_type')
    # ### end Alembic commands ###
