"""status

Revision ID: 946aa596f723
Revises: f44e658805a8
Create Date: 2025-12-31 09:11:04.973173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '946aa596f723'
down_revision: Union[str, Sequence[str], None] = 'f44e658805a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watermark_verify'), table_name='watermarks')
    op.create_index('ix_watermark_verify', 'watermarks', ['id', 'content_hash', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_watermark_verify', table_name='watermarks')
    op.create_index(op.f('ix_watermark_verify'), 'watermarks', ['id', 'content_hash'], unique=False)
    # ### end Alembic commands ###
