"""refactor table

Revision ID: 9b325acb766f
Revises: 8ab9310b722b
Create Date: 2025-12-28 19:13:28.218885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9b325acb766f'
down_revision: Union[str, Sequence[str], None] = '8ab9310b722b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watermarks', 'owner_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('watermarks', 'content_type',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Enum('image', 'video', 'audio', 'document', name='content_type_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watermarks', 'content_type',
               existing_type=sa.Enum('image', 'video', 'audio', 'document', name='content_type_enum'),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('watermarks', 'owner_id',
               existing_type=sa.String(length=36),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
