"""refactor table 2

Revision ID: f44e658805a8
Revises: 20415591837a
Create Date: 2025-12-28 22:37:49.250785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f44e658805a8'
down_revision: Union[str, Sequence[str], None] = '20415591837a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watermarks_asset_id'), table_name='watermarks')
    op.drop_index(op.f('ix_watermark_verify'), table_name='watermarks')
    op.create_index('ix_watermark_verify', 'watermarks', ['id', 'content_hash'], unique=False)
    op.drop_column('watermarks', 'issued_at')
    op.drop_column('watermarks', 'asset_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watermarks', sa.Column('asset_id', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('watermarks', sa.Column('issued_at', mysql.DATETIME(), nullable=False))
    op.drop_index('ix_watermark_verify', table_name='watermarks')
    op.create_index(op.f('ix_watermark_verify'), 'watermarks', ['asset_id', 'signature_hash', 'content_hash'], unique=False)
    op.create_index(op.f('ix_watermarks_asset_id'), 'watermarks', ['asset_id'], unique=False)
    # ### end Alembic commands ###
