"""nullable True

Revision ID: fce834c16a7a
Revises: 946aa596f723
Create Date: 2026-01-01 08:46:03.375045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fce834c16a7a'
down_revision: Union[str, Sequence[str], None] = '946aa596f723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watermarks', 'signature_hash',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('watermarks', 'content_hash',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watermarks', 'content_hash',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('watermarks', 'signature_hash',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
